### PR TITLE
Remove pify and @sindresorhus/is

### PR DESCRIPTION
**Pull request by sibiraj-s**
- Removed `pify` in favour of node's `util.promisify` available since v8.
- Removed `@sindresorhus/is` in favour of `lodash`

### CODE REVIEW

**Comment by sibiraj-s** [comment]
@niftylettuce we can also remove `@sindresorhus/is` in favour of lodash. Should I make the change as well?

**Comment by niftylettuce** [comment]
go for it

**Comment by sibiraj-s** [comment]
done.

**Comment by niftylettuce** [comment]
v7.2.0 released

https://github.com/forwardemail/email-templates/releases/tag/v7.2.0

thank you so much for your contribution @sibiraj-s ❤️ 🙏  hope you are well

**Comment by sibiraj-s** [comment]
Thanks @niftylettuce for the quick response.

> hope you are well

All good here. I hope you are doing good as well. 😄 🙏

**Pull request merged**
