### PR TITLE
custom path format for template files

### PR DESCRIPTION
**Pull request by ehsanonline**
I like to have all of my files and templates in root folder, instead of template folder, and organize them like this:
```
.
├── app.js
└── emails
    ├── mars.html.pug
    ├── mars.text.pug
    └── earth.html.pug
```
So I add a `path` key to `view` option, that is a path format for templates structure.
It's a string that could contain:
 * `<template>` as template name.
 * `<type>` as one of these file types: `html`,`text`,`subject`.
 * `<sep>` as the operating system path separator like `/` or `\` 

All of them will be replaced automatically.
For the example above, the path is `<template>.<type>`.
The default path is `<template><sep><type>`.

### CODE REVIEW

**Comment by ehsanonline** [comment]
I have no idea how the package-lock.json file get committed! in case you want to merge it, how can i delete it from the PR without making a new PR?!

**Comment by niftylettuce** [comment]
Can you please change this PR so that it is a function instead of a String?  The function would accept three arguments, `type`, `template`, `locals` and return a String.

**Comment by niftylettuce** [comment]
e.g. `const str = this.config.getPath(type, template, locals)` and `getPath = function(type, template) { return `${template}/${type}`; }`

**Comment by niftylettuce** [comment]
I've released this feature in v6.1.0.  See the README for `config.getPath` function.  Just pass your custom function and it should work.

I've also fixed it by default to use `path.sep` from Node's internal path package, so it should work better cross platform (e.g. instead of `${a}/${b}` it is now `path.join(a, b)`.

```sh
npm install email-templates@latest`
```

or with yarn

```sh
yarn add email-templates@latest
```

**Pull request closed without merging**
